config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  get 'analytics', to: 'search_logs#analytics'

  resources :articles do
    get :search, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/search_log.rb
class SearchLog < ApplicationRecord
  validates :query, presence: true
  validates :ip_address, presence: true

  def self.most_searched_term
    SearchLog.group(:query).count.max_by { |_, count| count }&.first
  end

  def self.total_searches
    SearchLog.count
  end

  def self.average_searches_per_user
    SearchLog.total_searches / SearchLog.distinct.count(:ip_address) if SearchLog.first.present?
  end

  def self.average_searches_per_day
    SearchLog.all.count / SearchLog.all.map(&:created_at).map(&:to_date).uniq.count
  end

  def self.query_counts
    most_searched_q = SearchLog.all.group_by(&:query).sort_by { |_, logs| -logs.count }.take(5)
    query_counts = {}
    most_searched_q.each do |query, logs|
      query_counts[query] = logs.count
    end
    query_counts
  end

  def self.analytics
    {
      most_searched_term: most_searched_term,
      total_searches: total_searches,
      average_searches_per_user: average_searches_per_user,
      average_searches_per_day: average_searches_per_day,
      most_searched_queries: query_counts.keys,
      query_counts: query_counts
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  # DELAY_BETWEEN_SEARCHES_IN_SECONDS = 30

  # GET /articles or /articles.json
  def index
    # @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show; end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit; end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    query = params[:query].strip.downcase
    ip = request.remote_ip
    user_logs = SearchLog.where(ip_address: ip)

    if user_logs.any? &&
       user_logs.last.updated_at > (Time.current - Constants::DELAY_BETWEEN_SEARCHES_IN_SECONDS.seconds) &&
       subquery_exists?(query, user_logs.last.query)

      user_logs.last.update(query:)
    else
      SearchLog.create(query:, ip_address: ip)
    end

    @articles = Article.where('name ILIKE ?', "%#{query}%")

    render json: { status: :ok, message: 'Success!', query:, results: @articles }
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:name)
  end

  def subquery_exists?(query, existing_query)
    query.include?(existing_query)
  end
end

app/controllers/search_logs_controller.rb
class SearchLogsController < ApplicationController
  def analytics
    @analytics_data = SearchLog.analytics
    render 'analytics'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/search_logs_helper.rb
module SearchLogsHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Name:</strong>
    <%= article.name %>
  </p>

</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<head>
    <meta charset="UTF-8">    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <%= stylesheet_link_tag 'article_search',media: 'all', data: { turbolinks: false } %>
    <%= stylesheet_link_tag 'header',media: 'all', data: { turbolinks: false } %>

    <% content_for :javascript do %>
      <%= javascript_include_tag 'articles/article_search' %>
    <% end %>
</head>
    <body>
        <%= render 'layouts/header', analytics_data: nil %>
        
        <div class="container">
            <div class="search-container">
                <div class="search-wrapper">
                    <div class="input-search">
                        <input type="search" id="search-input" class="search-box" placeholder="Type to search... e.g. iphone"/>
                        <i class="fas fa-search"></i>
                    </div>
                </div>
                <br/>
                <br/>
                <div id="spinner" class="spinner"></div>
            </div>
            <ul class="pills">
                <div id="search-results" class="search-results"></div> 
            </ul>
        </div>
    </body>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div>

app/views/layouts/_header.html.erb
<header>
    <div class="logo">
      <a class="logo" href= <%= articles_path %> >
        <%= image_tag("logo.png", height: 50, width: 50) %>
        <div class="logo-text">
        <h1>InstaSearch</h1>
        <h5>
            your search and&nbsp<b style="font-weight: bold; color: red;">analytics</b>&nbspengine
        </h5>
        </div>
      </a>
        <div class="analytics-tab">
        <ul>
            <% if analytics_data.present? %>
              <li><%= link_to 'InstaSearch for articles', articles_path %></li>
            <% else %>
              <li><%= link_to 'Analytics', analytics_path %></li>
            <% end %>
            <li><a href="#">About</a></li>
            <li><a href="#">Contact</a></li>
        </ul>
        </div>
        <div id="menu" class="hamburger-menu">
        <i class="fas fa-bars fa-3x"></i>
        </div>
    </div>

    <div id="side-nav" class="sidebar">
            <ul>
                <% if analytics_data.present? %>
                  <li><%= link_to 'InstaSearch for articles', articles_path %></li>
                <% else %>
                  <li><%= link_to 'Analytics', analytics_path %></li>
                <% end %>
                <li><a href="#">About</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
    </div>
      <%= javascript_include_tag 'header/header' %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstaSearch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= #javascript_importmap_tags 
    %>
    <%= yield :javascript %> <!-- Placeholder for page-specific JavaScript -->
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/search_logs/analytics.html.erb
<head>
    <meta charset="UTF-8">    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <%= stylesheet_link_tag 'header',media: 'all', data: { turbolinks: false } %>
    <%= stylesheet_link_tag 'analytics',media: 'all', data: { turbolinks: false } %>
</head>
    <body>
        <%= render 'layouts/header', analytics_data: @analytics_data %>

        <h1>Search analytics</h1>

        <% if @analytics_data[:query_counts].present? && 
            @analytics_data[:most_searched_term].present? && 
            @analytics_data[:total_searches].present? &&
            @analytics_data[:average_searches_per_day].present? &&
            @analytics_data[:average_searches_per_user].present?
        %>
        <table>
            <thead>
                <tr>
                    <th>Metric</th>
                    <th>Data</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Top 5 Searches</td>
                    <td>
                        <ul>
                            <% @analytics_data[:query_counts].each do |query, count| %>
                                <p><%= "#{query}: #{count}" %></p>
                            <% end %>
                        </ul>
                    </td>
                </tr>
                <tr>
                    <td>Most Searched Term</td>
                    <td>
                        <%= @analytics_data[:most_searched_term] %>
                    </td>
                </tr>
                <tr>
                    <td>Total Searches</td>
                    <td>
                        <%= @analytics_data[:total_searches] %>
                    </td>
                </tr>
                <tr>
                    <td>Average Searches per Day</td>
                    <td>
                        <%= @analytics_data[:average_searches_per_day] %>
                    </td>
                </tr>
                <tr>
                    <td>Average Searches per user</td>
                    <td>
                        <%= @analytics_data[:average_searches_per_user] %>
                    </td>
                </tr>
            </tbody>
        </table>
        <% else %>
            <p>We have just started, search more to see analytics!</p>
        <% end %>
    </body>